[2024-12-21T15:20:01.397+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.crear_archivo_fecha_task scheduled__2024-12-21T15:19:00+00:00 [queued]>
[2024-12-21T15:20:01.407+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.crear_archivo_fecha_task scheduled__2024-12-21T15:19:00+00:00 [queued]>
[2024-12-21T15:20:01.408+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T15:20:01.408+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-12-21T15:20:01.408+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T15:20:01.419+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): crear_archivo_fecha_task> on 2024-12-21 15:19:00+00:00
[2024-12-21T15:20:01.424+0000] {standard_task_runner.py:55} INFO - Started process 11896 to run task
[2024-12-21T15:20:01.428+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'commiteando_cosas', 'crear_archivo_fecha_task', 'scheduled__2024-12-21T15:19:00+00:00', '--job-id', '2147', '--raw', '--subdir', 'DAGS_FOLDER/elPataCommits.py', '--cfg-path', '/tmp/tmp_nn0w013']
[2024-12-21T15:20:01.428+0000] {standard_task_runner.py:83} INFO - Job 2147: Subtask crear_archivo_fecha_task
[2024-12-21T15:20:01.493+0000] {task_command.py:376} INFO - Running <TaskInstance: commiteando_cosas.crear_archivo_fecha_task scheduled__2024-12-21T15:19:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T15:20:01.548+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=commiteando_cosas
AIRFLOW_CTX_TASK_ID=crear_archivo_fecha_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-21T15:19:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-21T15:19:00+00:00
[2024-12-21T15:20:01.549+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elPataCommits.py", line 12, in create_date_file
    os.makedirs(output_path, exist_ok=True)  # Crear directorio si no existe
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/usr/'
[2024-12-21T15:20:01.556+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=commiteando_cosas, task_id=crear_archivo_fecha_task, execution_date=20241221T151900, start_date=20241221T152001, end_date=20241221T152001
[2024-12-21T15:20:01.564+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2147 for task crear_archivo_fecha_task ([Errno 13] Permission denied: '/root/usr/'; 11896)
[2024-12-21T15:20:01.570+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T15:20:01.590+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
