[2024-12-21T14:31:38.947+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customOperator.hello scheduled__2022-01-07T00:00:00+00:00 [queued]>
[2024-12-21T14:31:38.959+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customOperator.hello scheduled__2022-01-07T00:00:00+00:00 [queued]>
[2024-12-21T14:31:38.960+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T14:31:38.960+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T14:31:38.960+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T14:31:38.980+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello> on 2022-01-07 00:00:00+00:00
[2024-12-21T14:31:38.984+0000] {standard_task_runner.py:55} INFO - Started process 6902 to run task
[2024-12-21T14:31:38.989+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customOperator', 'hello', 'scheduled__2022-01-07T00:00:00+00:00', '--job-id', '1057', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpbhy6ekh0']
[2024-12-21T14:31:38.991+0000] {standard_task_runner.py:83} INFO - Job 1057: Subtask hello
[2024-12-21T14:31:39.069+0000] {task_command.py:376} INFO - Running <TaskInstance: customOperator.hello scheduled__2022-01-07T00:00:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T14:31:39.135+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customOperator
AIRFLOW_CTX_TASK_ID=hello
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-07T00:00:00+00:00
[2024-12-21T14:31:39.136+0000] {taskinstance.py:1851} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2024-12-21T14:31:39.147+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customOperator, task_id=hello, execution_date=20220107T000000, start_date=20241221T143138, end_date=20241221T143139
[2024-12-21T14:31:39.156+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1057 for task hello (execute() got an unexpected keyword argument 'context'; 6902)
[2024-12-21T14:31:39.167+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T14:31:39.194+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
