[2024-12-21T14:31:38.056+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customOperator.hello scheduled__2022-01-05T00:00:00+00:00 [queued]>
[2024-12-21T14:31:38.116+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customOperator.hello scheduled__2022-01-05T00:00:00+00:00 [queued]>
[2024-12-21T14:31:38.118+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T14:31:38.121+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T14:31:38.122+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T14:31:38.191+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello> on 2022-01-05 00:00:00+00:00
[2024-12-21T14:31:38.211+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customOperator', 'hello', 'scheduled__2022-01-05T00:00:00+00:00', '--job-id', '1055', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpv2fru8bx']
[2024-12-21T14:31:38.214+0000] {standard_task_runner.py:83} INFO - Job 1055: Subtask hello
[2024-12-21T14:31:38.204+0000] {standard_task_runner.py:55} INFO - Started process 6900 to run task
[2024-12-21T14:31:38.453+0000] {task_command.py:376} INFO - Running <TaskInstance: customOperator.hello scheduled__2022-01-05T00:00:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T14:31:38.670+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customOperator
AIRFLOW_CTX_TASK_ID=hello
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-05T00:00:00+00:00
[2024-12-21T14:31:38.673+0000] {taskinstance.py:1851} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2024-12-21T14:31:38.698+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customOperator, task_id=hello, execution_date=20220105T000000, start_date=20241221T143138, end_date=20241221T143138
[2024-12-21T14:31:38.723+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1055 for task hello (execute() got an unexpected keyword argument 'context'; 6900)
[2024-12-21T14:31:38.746+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T14:31:38.836+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
